# docker-compose.yml

version: "3.7"
services:
  postgres-docker:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: postgres-docker
    ports: 
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
  nodejs:
    image: nodejs-postgres
    depends_on:
      - postgres-docker
    ports:
      - '3000:3000'